### ISSUE TITLE
Create Criteria A: Planning

### ISSUE THREAD

**Issue by rajathie** [rajathie/foodBot#7]
http://ib.compscihub.net/wp-content/uploads/2015/04/A.pdf

**Comment by MarkusTiede** [comment]
- [ ] A client who has a problem, you describe the problem briefly.
  - You have a CONSULTATION with the client, and agree a solution.
- [ ] You briefly describe the suitability of your solution.
- [ ] You identify success criteria.

- [ ] Make sure you have all three parts

Word count: ~500 words.

**Comment by MarkusTiede** [comment]
Success criteria

1. **Integrate / plug-in** into existing / already established HMI (human machine interaction) systems such as a chat application
2. Easy **user interaction** with client by pre-defined commands
3. **Situation based responding** with workflows on choices made 
4. Lightweight, **self serviced on-boarding** as a client
5. **Administration view** with restricted access to kitchen staff only
6. **Event based notifications** to all involved parties including all clients and staff
7. User centric choices including **cancellation / undo of choices**

**Comment by MarkusTiede** [comment]
Part 1 reviewed in ODT - continue there.
